[package]
name = "vcd30_player"
version = "0.1.5"
edition = "2024"
authors = ["NimitzDEV"]
description = "A cross-platform player and interactive runtime for VCD 3.0 discs"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/NimitzDEV/vcd30player"
keywords = ["vcd", "player", "multimedia", "retro", "emulator"]
categories = ["multimedia::video", "multimedia::audio", "emulators"]

[dependencies]
eframe = "0.36.1"
rfd = "0.17.2"
rodio = "0.20"

[build-dependencies]
cc = "1.2"
